# Taken from https://github.com/Alamofire/AlamofireImage
language: swift
osx_image: xcode10.2
env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
  matrix:
    - DESTINATION="OS=5.2,name=Apple Watch Series 4 - 44mm" SCHEME="Locksmith watchOS" SDK=watchsimulator RUN_TESTS="NO" BUILD_EXAMPLE="NO" POD_LINT="YES"
    - DESTINATION="OS=4.2,name=Apple Watch Series 3 - 42mm" SCHEME="Locksmith watchOS" SDK=watchsimulator RUN_TESTS="NO" BUILD_EXAMPLE="NO" POD_LINT="NO"
    - DESTINATION="OS=3.2,name=Apple Watch Series 2 - 42mm" SCHEME="Locksmith watchOS" SDK=watchsimulator RUN_TESTS="NO" BUILD_EXAMPLE="NO" POD_LINT="NO"
    - DESTINATION="OS=2.2,name=Apple Watch - 42mm" SCHEME="Locksmith watchOS" SDK=watchsimulator RUN_TESTS="NO" BUILD_EXAMPLE="NO" POD_LINT="NO"

    - DESTINATION="arch=x86_64" SCHEME="Locksmith OS X" SDK=macosx RUN_TESTS="YES" BUILD_EXAMPLE="NO" POD_LINT="NO"

    # "build_example" should be YES but travis was giving me grief
    - DESTINATION="OS=12.0,name=iPad Air 2" SCHEME="Locksmith iOS" SDK=iphonesimulator RUN_TESTS="YES" BUILD_EXAMPLE="NO" POD_LINT="NO"
    - DESTINATION="OS=12.1,name=iPhone XS" SCHEME="Locksmith iOS" SDK=iphonesimulator RUN_TESTS="YES" BUILD_EXAMPLE="NO" POD_LINT="NO"
    - DESTINATION="OS=12.2,name=iPhone XS Max" SCHEME="Locksmith iOS" SDK=iphonesimulator RUN_TESTS="YES" BUILD_EXAMPLE="NO" POD_LINT="NO"

    - DESTINATION="OS=11.2,name=iPad Air 2" SCHEME="Locksmith iOS" SDK=iphonesimulator RUN_TESTS="YES" BUILD_EXAMPLE="NO" POD_LINT="NO"
    - DESTINATION="OS=11.3,name=iPhone XS" SCHEME="Locksmith iOS" SDK=iphonesimulator RUN_TESTS="YES" BUILD_EXAMPLE="NO" POD_LINT="NO"
    - DESTINATION="OS=11.4,name=iPhone XS Max" SCHEME="Locksmith iOS" SDK=iphonesimulator RUN_TESTS="YES" BUILD_EXAMPLE="NO" POD_LINT="NO"

    - DESTINATION="OS=10.1,name=iPad Air 2" SCHEME="Locksmith iOS" SDK=iphonesimulator RUN_TESTS="YES" BUILD_EXAMPLE="NO" POD_LINT="NO"
    - DESTINATION="OS=10.2,name=iPhone 7" SCHEME="Locksmith iOS" SDK=iphonesimulator RUN_TESTS="YES" BUILD_EXAMPLE="NO" POD_LINT="NO"
    - DESTINATION="OS=10.3.1,name=iPhone 7 Plus" SCHEME="Locksmith iOS" SDK=iphonesimulator RUN_TESTS="YES" BUILD_EXAMPLE="NO" POD_LINT="NO"

    - DESTINATION="OS=9.1,name=iPad 2" SCHEME="Locksmith iOS" SDK=iphonesimulator RUN_TESTS="YES" BUILD_EXAMPLE="NO" POD_LINT="NO"
    - DESTINATION="OS=9.2,name=iPhone 6" SCHEME="Locksmith iOS" SDK=iphonesimulator RUN_TESTS="YES" BUILD_EXAMPLE="NO" POD_LINT="NO"
    - DESTINATION="OS=9.3,name=iPhone 6 Plus" SCHEME="Locksmith iOS" SDK=iphonesimulator RUN_TESTS="YES" BUILD_EXAMPLE="NO" POD_LINT="NO"

    - DESTINATION="OS=8.1,name=iPad 2" SCHEME="Locksmith iOS" SDK=iphonesimulator RUN_TESTS="YES" BUILD_EXAMPLE="NO" POD_LINT="NO"
    - DESTINATION="OS=8.2,name=iPhone 4S" SCHEME="Locksmith iOS" SDK=iphonesimulator RUN_TESTS="YES" BUILD_EXAMPLE="NO" POD_LINT="NO"
    - DESTINATION="OS=8.3,name=iPhone 5" SCHEME="Locksmith iOS" SDK=iphonesimulator RUN_TESTS="YES" BUILD_EXAMPLE="NO" POD_LINT="NO"
    - DESTINATION="OS=8.4,name=iPhone 5S" SCHEME="Locksmith iOS" SDK=iphonesimulator RUN_TESTS="YES" BUILD_EXAMPLE="NO" POD_LINT="NO"
before_install:
  - gem install cocoapods --no-document --quiet
  - gem install xcpretty --no-document --quiet
script:
  - set -o pipefail
  - xcodebuild -version

  # Build and run tests in Debug and Release
  - if [ $RUN_TESTS == "YES" ]; then
    xcodebuild -workspace Locksmith.xcworkspace -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION"
      -configuration Debug ONLY_ACTIVE_ARCH=NO test | xcpretty -c;
    fi
  - if [ $RUN_TESTS == "YES" ]; then
      xcodebuild -workspace Locksmith.xcworkspace -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION"
        -configuration Release ONLY_ACTIVE_ARCH=NO test | xcpretty -c;
    fi

  # Only build in Debug and Release
  - if [ $RUN_TESTS == "NO" ]; then
    xcodebuild -workspace Locksmith.xcworkspace -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION"
      -configuration Debug ONLY_ACTIVE_ARCH=NO | xcpretty -c;
    fi
  - if [ $RUN_TESTS == "NO" ]; then
      xcodebuild -workspace Locksmith.xcworkspace -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION"
        -configuration Release ONLY_ACTIVE_ARCH=NO | xcpretty -c;
    fi

  # Build example in Debug and Release
  - if [ $BUILD_EXAMPLE == "YES" ]; then
      xcodebuild -workspace Locksmith.xcworkspace -scheme "Locksmith iOS Example" -sdk "$SDK" -destination "$DESTINATION"
        -configuration Debug ONLY_ACTIVE_ARCH=NO build | xcpretty -c;
    fi
  - if [ $BUILD_EXAMPLE == "YES" ]; then
      xcodebuild -workspace Locksmith.xcworkspace -scheme "Locksmith iOS Example" -sdk "$SDK" -destination "$DESTINATION"
        -configuration Release ONLY_ACTIVE_ARCH=NO build | xcpretty -c;
    fi

  # Run pod lib lint quick if specified
  - if [ $POD_LINT == "YES" ]; then
      pod lib lint;
    fi
